# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download case data
      run: |
        python run.py
    - name: Archive data
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: LAGeSo.csv
    - name: push
              run: |
                  git config --global user.name 'autocommit'
                  git config --global user.email 'autocommit@users.noreply.github.com'
                  git add --all
                  git commit --allow-empty -m "Github Action autocommit"
                  git push
    
